### ISSUE TITLE
Game creation form crashes when selecting pyramid variant

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#163]
Not sure what exactly causes the error.

Steps to reproduce:
Select pyramid in the variant dropdown in the game creation form -> the form collapses and console shows error "TypeError: t is undefined"

**Comment by benjaminpjones** [comment]
Ah this is a weird one, thanks for finding it.

I think the root cause is that we construct a game object, in order to get the default config:

```
export function getDefaultConfig(variant: string) {
  const game = new game_map[variant]();
  return game.defaultConfig();
}
```

However, instantiating PyramidGo requires a width and a height...

```
  constructor(config: BadukConfig) {
    this.weights = new Grid(config.width, config.height)
  }
```

By design, the type system is pretty broken around variants/configs/`game_map`.  I'll need to think more about that. And please let me know if you have thoughts on that as well.

But for the short term fix, I recommend we separate configs from the game instances, since they don't depend on a constructed object.   We could potentially stick it in the `game_map`, something like:

```
const DEFAULT_BADUK_CONFIG = { width: 19, height: 19, komi: 7 };
const game_map = {
  baduk: { class: Baduk, defaultConfig: DEFAULT_BADUK_CONFIG },
  pyramid: { class: PyramidGo, defaultConfig: DEFAULT_BADUK_CONFIG },
}
```

```
export function getDefaultConfig(variant: string) {
  return game_map[variant].defaultConfig;
}
```

**Comment by merowin** [comment]
I agree, I think it makes sense that the config (default or not) exists before the game object. At the moment its kindof the other way around.

**Comment by JonKo314** [comment]
> Edit: maybe the method defaultConfig could be static

I was thinking that too

**Comment by benjaminpjones** [comment]
`static` sounds good, but if I recall, I ran into some issues making an `abstract static` member: https://github.com/microsoft/TypeScript/issues/34516

Is there a way we can work around that?

**Comment by JonKo314** [comment]
Ah, I forgot about that. Also there would be another issue: 
> Static members cannot reference class type parameters. ts(2302)

Then I'd be fine with your suggestion, @benjaminpjones.
