### ISSUE TITLE
[Keima] game can reach a dead-end state

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#189]
Steps to reproduce:

Navigate the game s.t. one of the players plays a move where no follow-up keima is possible. For example:

![grafik](https://github.com/govariantsteam/govariants/assets/77507448/c2410096-330b-489b-b57a-d2b4034cd545)
The lone white stone was the last move, now white has no legal moves and the game is stuck without being over.

The rule description on the EGC site doesn't specify what should happen in such a case: https://www.egc2023.de/schedule/keima-go-2-2/

I think the following rulings would all be reasonable.
- The first move is already illegal (given that there is no legal follow-up)
- The second move is skipped
- The first move can be taken back

**Comment by merowin** [comment]
I just realised that it's not really a dead-end, as passing still works. So I guess that's perfectly fine, apologies!

**Comment by merowin** [comment]
closing because it works (second move can be skipped by passing).

**Comment by benjaminpjones** [comment]
So, I guess that's equivalent to "The second move is skipped", but it wasn't intentional haha.  I would accept the interpretation that two non-pass moves must be played :)

It seems a little more clear in these descriptions:

- "you have to place two stones instead of just one on each turn you don't pass"  ([Senseis Library](https://senseis.xmp.net/?KeimaGo))
- "Ein Keima-Go-Zug besteht aus zwei direkt nacheinander gespielten einzelnen Go-Zügen (einer Farbe), die zusammen die Form eines Keimas (Rösselsprung) bilden müssen." [Hannoverscher Go-Verein e.V.](http://www.hannover-go.de/Keima-Go/Keima-Go.html)
   - This one seems less ambiguous because a stone and a pass cannot form a keima.
