### ISSUE TITLE
[quantum] Wrong player given the win for resignation

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#333]
https://www.govariants.com/game/673a1ad0ac18ee7204eab931

The UI says *B+R*, but the last move is `{"0": "resign"}`

**Comment by SameerDalal** [comment]
Found the issue in the `playMove` function in `quantum.ts`

Instead of `this.result = player === 0 ? "B+R" : "W+R";` it should be `this.result = player === 0 ? "W+R" : "B+R";`

If player is 0 (black), then the result should be "W+R"

Also, I think the same issue is happening with timeout. The B+T and W+T should be swapped

**Comment by benjaminpjones** [comment]
Correct!
